# Generated by Django 6.0.6 on 2026-06-06 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Token de Restablecimiento', 'verbose_name_plural': 'Tokens de Restablecimiento'},
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='cuentas_pas_expires_f6557c_idx',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_column='expires_at', db_index=True),
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='expires_at',
            new_name='expira_en',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used',
            field=models.BooleanField(db_column='used', default=False),
        ),
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='used',
            new_name='utilizado',
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expira_en', 'utilizado'], name='cuentas_pas_expires_f6557c_idx'),
        ),
    ]
