# Generated by Django 6.0.3 on 2026-03-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0005_alter_rol_options_alter_rol_descripcion_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
