# Generated by Django 5.2.8 on 2026-03-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0006_envio_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='rechazada',
            field=models.BooleanField(default=False),
        ),
    ]
