# Generated by Django 6.0.6 on 2026-06-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0007_envio_rechazada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='user',
            new_name='usuario',
        ),
    ]
